import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "@/components/provider/ClientProviders";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "TaskNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
